### ISSUE TITLE
Mod does not load (1.15.2 31.2.47 Forge)  [Fixed]

### ISSUE THREAD

**Issue by MrCreeps** [cctvcraft/cctvcraft#4]
**Describe the bug**

**To Reproduce**
Install and play the mod

**Expected behavior**
The game to launch properly

**Screenshots**
![image](https://user-images.githubusercontent.com/75145015/115777380-ce745480-a37a-11eb-9874-a7d62219a1ef.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 3.0.0

**Additional context**
The game does not work. I used 1.15.2 31.2.47 Forge.

**Comment by northwesttreesgaming** [comment]
Can you provide a debug.log file.

**Comment by MrCreeps** [comment]
https://pastebin.com/pDnGXV46
I pasted the log on pastebin.

**Comment by MrCreeps** [comment]
Using the 1.15.2 31.2.50 forge also gives me the same error. So it is not be using an outdated forge version. I'm not sure whether or not you need the debug for the new test with the most recent forge but I can provide it if you need it.

**Comment by northwesttreesgaming** [comment]
Thank you for posting the log. 

I read a bit of it over and I did not notice any part of the mod causing the exact issue, it may be a conflict with the main menu of the game and some kind of GUI in that version of forge. The mod was made on the recommended build for Forge 31.2.0, if possible, I suggest using that build as it is more stable for the mod and has been tested on that build of Forge.

**Comment by MrCreeps** [comment]
I installed and used the mod with the 1.15.2 31.2.0 and still received the same error :/

**Comment by MrCreeps** [comment]
In the latest.log it mentions this

"Caused by: java.lang.NoSuchMethodError: net.minecraft.client.gui.ScreenManager.registerFactory(Lnet/minecraft/inventory/container/ContainerType;Lnet/minecraft/client/gui/ScreenManager$IScreenFactory;)V
	at net.nwtg.cctvcraft.gui.MonitorConnectionScreenGui.lambda$initElements$0(MonitorConnectionScreenGui.java:58) ~[?:?]
	at net.nwtg.cctvcraft.gui.MonitorConnectionScreenGui$$Lambda$2424/1598159456.run(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) ~[?:1.8.0_51]
	... 41 more"

**Comment by northwesttreesgaming** [comment]
I mist that section. Indeed this is important "MonitorConnectionScreenGui" is the monitor's GUI for remote connection where you can connect cameras from the monitor. Most likely there is a conflict for some reason. I am not sure what the conflict would be with but assuming you don't have any other mods except for MMP UUID and CCTVCraft then it's most likely something to do with the base game or forge its self.

I actually have been thinking of a better way to work in the camera connection system using remote floppy disks I was hoping to go with an inventory system that the monitor can read NBT from items in the slots, I have not tested it yet but if this works this would also fix this issue with that screen. As it would no longer be needed.

I thank you for bringing this to my attention, I am really sorry I can't push out a patch for 3.0.0.

**Comment by MrCreeps** [comment]
I understand. Does it work when you launch the mod? I could try to do a test on my older desktop to see if it works there.

**Comment by northwesttreesgaming** [comment]
I was able to run it on my Windows 10 64 Bit OS.
I am not sure if testing it on another computer would do much at the moment as I have to rebuild the mod before I can know for sure. If you would like to try to run it on your older desktop this should be fine. Feel free to let me know how it goes if you try ;)

**Comment by northwesttreesgaming** [comment]
I spoke with some of the MCToolkit devs. The code may have needed to be generated. 

Sadly I don't have the exact build to do that so I will have to mark this as closed.
3.1.0 will support 1.15.2 and 1.16.5 and have more features when it's released as well as a backed-up build.

**Comment by MrCreeps** [comment]
Hello, I tested it on my desktop and it worked flawlessly (besides the 20 minute loading time since it’s pretty bad). It is probably something with my laptop :/ It runs other mods fine though so I don’t know.

**Comment by MrCreeps** [comment]
One thing I want to mention is that I used the download from CurseForge on my tests on my desktop, but on my laptop I used the version from GitHub, I will do a test on the GitHub version tomorrow.

**Comment by MrCreeps** [comment]
Okay, it works I downloaded the CCTV Craft file from CurseForge and it works on my laptop, but when I try to open a world it crashes and gives this error - 
https://pastebin.com/5UfgBZXC

**Comment by northwesttreesgaming** [comment]
This seems to be on MMP UUIDs side this time, I will look into the issue, I have that workspace still sho I may be able to fix that problem.

**Comment by northwesttreesgaming** [comment]
See if this fixes the issue. It may have been an issue with how some of the variables were set up in MMP UUID.
The lag could have been partly this mod too. 

[mmpuuid_v1.3.0_mc1.15.2.zip](https://github.com/cctvcraft/cctvcraft/files/6443330/mmpuuid_v1.3.0_mc1.15.2.zip)

**Comment by northwesttreesgaming** [comment]
When you get a chance can you try the mmp version to see if it resolved the lag you were having.
It should only be running when the player joins the world now not every player tick update so this should help a bit with performance.

**Comment by northwesttreesgaming** [comment]
This has to do with the dependence of MMP UUID, the other mod I made for
the ownership system.
https://github.com/NorthWestTrees-Minecraft-Mods/mmp_unique_user_ids
If you don't already have the regular download for 1.15.2 installed then
try installing that mod with CCTV Craft.
Use the Regular download version though as the other one is for the test
environment.
If it still causes you issues then it may be something on MMP UUID's End of
things.
